FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build

WORKDIR /app

COPY . ./

# Publish app and libraries
RUN dotnet publish -f netcoreapp3.1 -c Release -o out

FROM mcr.microsoft.com/dotnet/core/runtime:3.1-alpine-arm64v8
WORKDIR /app
COPY --from=build /app/out ./

RUN useradd -ms /bin/bash moduleuser
USER moduleuser

ENTRYPOINT ["dotnet", "SampleContainer.dll"]